//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commod
    {
        public System.Guid ID { get; set; }
        public string MerName { get; set; }
        public string Name { get; set; }
        public string Line { get; set; }
        public string Axes { get; set; }
        public string ValueAdd { get; set; }
        public long Price { get; set; }
        public string DateTimes { get; set; }
    }
}
