//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace DataAccesss
{

    public partial class RxjhEntities : DbContext
    {
        public RxjhEntities()
            : base("name=RxjhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SystemConfig> SystemConfig { get; set; }
        public DbSet<CommodConfig> CommodConfig { get; set; }
        public DbSet<Commod> Commod { get; set; }
    }
}
